name: Upload Python Package

on:
  workflow_dispatch:
  push:

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get install -y libsndfile-dev ffmpeg
        python -m pip install --quiet --upgrade pip
        pip install --quiet hatch
        pip install ".[torch, test]"
        pip list | grep torch

    - name: Test
      env:
        CUDA_VISIBLE_DEVICES: ""
      run: hatch -v run pytest .

    - name: Build dist and Publish on TestPypi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        hatch version pre
        hatch clean
        hatch build
        hatch publish -r test -u ${{ env.TWINE_USERNAME }}
